server:
  port: 8082

app:
  config:
    a: jsdsd
    b: asdas
    x: 09867

spring:
  cloud:
    openfeign:
      client:
        config:
          jsonPlaceholderClient:
            url: https://localhost:8081
            connectTimeout: 5000
            readTimeout: 100
            headers:
              X-Custom-Header: "Change Header"
              Content-Type: "application/json"