server:
  port: 8082

app:
  config:
    a: jsdsd
    b: asdas
    x: 09867
  other:
    prop1: change Value

spring:
  cloud:
    openfeign:
      client:
        config:
          jsonPlaceholderClient:
            url: https://jsonplaceholder.typicode.com
            connectTimeout: 5000
            readTimeout: 1
            headers:
              X-Custom-Header: "Change Header"
              Content-Type: "application/json"